# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 9000, host: 9002

  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
	v.cpus = 2
  end
  
  config.vm.provision "shell", path: "scala.sh"
end
